nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: ""
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort:

env:
  useConfigMap: false
  useSecret: false

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

externalSecret:
  enabled: false
  refreshInterval: "1h"
  secretStore:
    kind: SecretStore
    name: aws-secret-store
  dataFromKey: ""

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 300m
    memory: 384Mi

affinity: {}