{{- define "base-template.external-secret" }}
{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "base-template.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStore.kind }}
    name: {{ .Values.externalSecret.secretStore.name }}
  target:
    name: {{ include "base-template.fullname" . }}-secret
  dataFrom:
    - extract:
        key: {{ .Values.externalSecret.dataFromKey }}
{{- end }}
{{- end }}